[tool.poetry]
name = "pa"
version = "0.1.0"
description = "Aplicativo CLI para calcular níveis e projeções de price action"
authors = ["Valmir França <vfranca3@gmail.com>"]
license = "BSD-3-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.8"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-env = "^1.1.5"
pytest-cov = "^6.0.0"

[tool.poetry.scripts]
pa = "pa.pa:pa"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
